### ISSUE TITLE
Crashes on iOS, maybe because of optim level (-O1, -O2 ...). Add a way to change it?

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/hxcpp#764]
I am having GC crashes on iOS (I believe, similar to [these emscripten crashes](https://github.com/HaxeFoundation/hxcpp/issues/760). Reproduced on a big project that uses a lot of closures that capture variables etc... on iPhone SE, arm64).

Checked ``iphoneos-toolchain.xml`` and replaced ``<flag value="-O2" unless="debug"/>`` with ``<flag value="-O1" unless="debug"/>`` and the crashes seem to have disappeared.

I noticed that there is a HXCPP_OPTIM_LEVEL define on emscripten toolchain. I think this define would be useful for iOS as well.

At the moment I have to patch the toolchain file to limit optims to ``-O1``. Not sure if this should become the default if more agressive optims create issues, but at least we should be able to change it.

**Comment by hughsando** [comment]
Adding HXCPP_OPTIM_LEVEL seems like a reasonable fix for now.  It is possible that this could be better fixed with better native register capture specifically for the ARM64 architecure.  It has been a while since I've looked at this but there should be a way to do it.

**Comment by PaulGene** [comment]
Thank you jeremyfa, I've been having seemingly unfix-able crashes on 64bit iOS (32bit was fine) devices for ages now, I tried this and they have gone!

I think O1 should be default on 64bit iOS devices for now as this is probably causing a lot of people problems.

**Comment by sorka95032** [comment]
TiVo is having the same issue.

**Comment by PaulGene** [comment]
I reiterate this only seems to effect iOS 64bit devices, so old 32bit devices can still have the extra optimisations without issues and from my tests they need it, it had quite a big impact on performance.

So, I'm doing this:

  <flag value="-O1" if="HXCPP_ARM64" unless="debug"/>
  <flag value="-O2" unless="debug || HXCPP_ARM64"/>

**Comment by ncannasse** [comment]
@hughsando regarding register capture, in HL I'm using a setjmp to store the registers into a jmp_buf and scanning it to look for pointers. It is quite crossplatform IMHO.

**Comment by hughsando** [comment]
I am not currently setup to test this, but I have added some experimental setjmp register capture with https://github.com/HaxeFoundation/hxcpp/commit/c392f53e952118d1b29d498fc07d5481e22888de

You can test it by uncommenting the "#define HXCPP_CAPTURE_SETJMP" in src/hx/gc/GcRegCapture.h

Let me know how it goes.

**Comment by jeremyfa** [comment]
Getting back to this subject, sorry for the delay and thanks for the fix! I will try to use `HXCPP_CAPTURE_SETJMP` + `-O2` on iOS and will tell you how it goes!

**Comment by jeremyfa** [comment]
While I was not able to reproduce these issues locally, I noticed a pattern when taking a closer look at reported crash logs on a Haxe/CPP game in production with thousands daily active users that may be related to this. The crashes usually happen when we have nested calls of closures.

I published a new version of the app yesterday with `HXCPP_CAPTURE_SETJMP` enabled. I will keep you posted to tell if that solve these issues or not.

Need to wait for a few days to see if the new version is still reporting those crashes or if they indeed disappeared (I hope so🤞)

**Comment by hughsando** [comment]
I think some registers may be missed on Arm64.  See the comments at the bottom of: https://github.com/HaxeFoundation/hxcpp/issues/945 
I am interested to see if SETJMP fixes it.

**Comment by jeremyfa** [comment]
Some feedback after one week of the updated app being in production:
- Some crashes didn't appear again. They were pretty random and not very frequent, so it doesn't really mean it was solved
- Some other crashes still remain (INVALID ADDRESS from hx::GCSetHaxeFinalizer, called from Sqlite.cpp), when using nested closures, and where the first closure is called from another thread. I have yet to determine if that's some edge case that HXCPP's GC can't handle or if there is another issue involved in my code. Interested to try the arm64 fixes at some point to see if that makes a difference, but ideal would be that I succeed to setup a project that stress test this feature to try to get the crash locally, which will make it easier to track down and to test other options (like the ARM64 fixes you mentioned)

Will continue to check my app in production to see if some crashes are really gone or not!
